baseurl = "/"
languageCode = "en-us"
title = "Gomematic"
disableKinds = ["RSS"]

[params]
  Description = "Lightweight and powerful Homematic"
  Author = "Gomematic Team"
  Website = "https://gomematic.webhippie.de"
  Github = "gomematic"
